### ISSUE TITLE
Error with spell throw 2764

### ISSUE THREAD

**Issue by radicalhashcan** [RekzaiSharp/WildcardRoll#5]
![image](https://user-images.githubusercontent.com/42519202/94464924-bf327d00-0184-11eb-95fc-ca0a9687bb68.png)

**Comment by radicalhashcan** [comment]
Fixed, do you allow pushes?

**Comment by DkVagabonden** [comment]
Could you share it? :)

**Comment by Yzeyr** [comment]
Wait, so how do you fix this?

**Comment by Duellinkspc** [comment]
Having the same issue

**Comment by Se11fish** [comment]
id be interested in the solution aswell!

**Comment by SneakyShaman** [comment]
Very interested in a solution as well

**Comment by radicalhashcan** [comment]
https://raw.githubusercontent.com/RekzaiSharp/WildcardRoll/master/WildcardRoll/Database.cs
![image](https://user-images.githubusercontent.com/42519202/106743119-9105f380-65e3-11eb-9d31-9c90b0a77803.png)
should look like this after you update with the spellid.

**Comment by isi89** [comment]
Hi radicalhashcan.

Can you post the fixed version of this application, or show us how to fix it ourselves. I don't think the original creator will update its code. Can you show us how to replace the code in Database.cs and make it run the app?

TNX!

**Comment by bodacsani** [comment]
Please fix it :(

**Comment by mnpenchev** [comment]
Author is long time gone, can someone update this issue ?

**Comment by RekzaiSharp** [comment]
Please move to https://github.com/Shawak for any issues as he is the one maintaining this project.
